### ISSUE TITLE
devbuild.sh failing when installing unbound on centos 8.2 (x86)

### ISSUE THREAD

**Issue by johnjore** [E-F-A/v4#201]
Hi!

devbuild.sh is now failing (for me) on a newly build CentOS 8.0 upgraded to 8.2 (x64/x86).
Install of Unbound has failed build dependencies: expat-devel, flex, libevent-devel, python3-devel and swig.

If I install these and re-run, it fails with:

```
Error:
 Problem: conflicting requests
  - nothing provides unbound >= 1.11.0-1 needed by eFa-1:4.0.3-11.eFa.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

```
Using https://github.com/johnjore/v4 it runs to the end without issues, and unbound -v shows it's installed 1.7.3.

**Comment by shawniverson** [comment]
Fixed in commit 06735d4d4310e080df754b69e667e677833fd5ed

**Comment by johnjore** [comment]
Hm.... I think this needs a little more work as I still have issues with unbound on CentOS 8.2:

```
Error:
 Problem: conflicting requests
  - nothing provides unbound >= 1.11.0-1 needed by eFa-1:4.0.3-11.eFa.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

```
yum -y install $GITPATH/rpmbuild/RPMS/`uname -m`/unbound-*.rpm

```
Last metadata expiration check: 0:09:10 ago on Tue 27 Oct 2020 02:06:15 PM AEDT.
Error:
 Problem: problem with installed package python3-unbound-1.7.3-11.el8_2.x86_64
  - package python3-unbound-1.7.3-11.el8_2.x86_64 requires libunbound.so.2()(64bit), but none of the providers can be installed
  - package python3-unbound-1.7.3-11.el8_2.x86_64 requires unbound-libs(x86-64) = 1.7.3-11.el8_2, but none of the providers can be installed
  - cannot install both unbound-libs-1.11.0-1.eFa.el8.x86_64 and unbound-libs-1.7.3-11.el8_2.x86_64
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

```

**Comment by johnjore** [comment]
This may, or may not be a good idea, but running `yum remove python3-unbound` lets the install complete.

**Comment by shawniverson** [comment]
Fixed in commit 7c6c05b6c09352e3604ca1ead9a61df273649074
